DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
	`user_id`	BIGINT(20)	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`id`	VARCHAR(100)	NOT NULL,
	`password`	VARCHAR(255)	NOT NULL,
	`name`	VARCHAR(100)	NOT NULL,
	`email`	VARCHAR(255)	NOT NULL,
	`phone`	VARCHAR(20)	NOT NULL,
	`birth`	VARCHAR(100)	NULL,
	`address`	VARCHAR(255)	NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`role`	VARCHAR(100)	NOT NULL
);

DROP TABLE IF EXISTS `Dday`;

CREATE TABLE `Dday` (
	`day_id`	BIGINT(20)	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`user_id`	BIGINT(20)	NOT NULL,
	`tag_id`	BIGINT(20)	NOT NULL,
	`date`	DATE	NOT NULL,
	`title`	VARCHAR(255)	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`display_main`	INT	NOT NULL	DEFAULT 0,
	`notification_enabled`	INT	NOT NULL	DEFAULT 0
);

DROP TABLE IF EXISTS `product`;

CREATE TABLE `product` (
	`product_id`	BIGINT(20)	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`category_id`	BIGINT(20)	NOT NULL,
	`tag_id`	BIGINT(20)	NOT NULL,
	`name`	VARCHAR(255)	NOT NULL,
	`price`	INT	NOT NULL,
	`stock`	INT	NOT NULL,
	`platform_url`	VARCHAR(255)	NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `product_category`;

CREATE TABLE `product_category` (
	`category_id`	BIGINT(20)	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name`	VARCHAR(255)	NOT NULL,
	`parent_id`	BIGINT(20)	NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `anniversary_type`;

CREATE TABLE `anniversary_type` (
	`anniversary_id`	BIGINT(20)	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`calculation_id`	BIGINT(20)	NOT NULL,
	`name`	VARCHAR(255)	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `relationship_type`;

CREATE TABLE `relationship_type` (
	`relationship_id`	BIGINT(20)	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name`	VARCHAR(255)	NOT NULL,
	`target_age`	INT	NULL,
	`target_gender`	VARCHAR(10)	NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `calculation_type`;

CREATE TABLE `calculation_type` (
	`calculation_id`	BIGINT(20)	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name`	VARCHAR(255)	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`description`	TEXT	NOT NULL
);

DROP TABLE IF EXISTS `notification`;

CREATE TABLE `notification` (
	`notification_id`	BIGINT(20)	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`product_id`	BIGINT(20)	NOT NULL,
	`day_id`	BIGINT(20)	NOT NULL,
	`title`	VARCHAR(255)	NOT NULL,
	`message`	TEXT	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`enabled`	INT	NOT NULL	DEFAULT 0
);

DROP TABLE IF EXISTS `persistent_logins`;

CREATE TABLE `persistent_logins` (
	`username`	VARCHAR(255)	NOT NULL PRIMARY KEY,
	`series`	VARCHAR(255)	NOT NULL,
	`token`	VARCHAR(255)	NOT NULL,
	`last_used`	VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `file`;

CREATE TABLE `file` (
	`file_id`	BIGINT(20)	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`day_id`	BIGINT(20)	NOT NULL,
	`product_id`	BIGINT(20)	NOT NULL,
	`type`	VARCHAR(100)	NOT NULL,
	`name`	VARCHAR(100)	NOT NULL,
	`path`	VARCHAR(100)	NOT NULL,
	`size`	INT	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `tag`;

CREATE TABLE `tag` (
	`tag_id`	BIGINT(20)	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`anniversary_id`	BIGINT(20)	NOT NULL,
	`relationship_id`	BIGINT(20)	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `product_tag`;

CREATE TABLE `product_tag` (
	`product_id`	BIGINT(20)	NOT NULL PRIMARY KEY,
	`tag_id`	BIGINT(20)	NOT NULL PRIMARY KEY,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
